version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  nx-ms-server-gateway:
    build: ./nx-ms-server-gateway
    container_name: nx-ms-server-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://nx-ms-server-auth:3001
      - EVENT_SERVICE_URL=http://nx-ms-server-event:3002
      - JWT_SECRET=this-is-a-secret-key-for-my-jwt-token-this-is-super-top-secret
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
      - nx-ms-server-auth
      - nx-ms-server-event
    networks:
      - app-network
    volumes:
      - ./nx-ms-server-gateway:/app
    restart: on-failure
    command: yarn start:dev

  nx-ms-server-auth:
    build: ./nx-ms-server-auth
    container_name: nx-ms-server-auth
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your-auth-jwt-secret
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./nx-ms-server-auth:/app
    restart: on-failure
    command: yarn start:dev

  nx-ms-server-event:
    build: ./nx-ms-server-event
    container_name: nx-ms-server-event
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./nx-ms-server-event:/app
    restart: on-failure
    command: yarn start:dev

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: