
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - app-network

  nx-ms-server-gateway:
    build:
      context: ./nx-ms-server-gateway
      dockerfile: Dockerfile.local
    container_name: nx-ms-server-gateway
    ports:
      - "3000:3000"
    environment:
      - SERVER_GATEWAY_AUTH_PREFIX=/api/auth
      - SERVER_GATEWAY_EVENT_PREFIX=/api/event
      - GATEWAY_SERVICE_URL=http://nx-ms-server-gateway:3000
      - AUTH_SERVICE_URL=http://nx-ms-server-auth:3000
      - EVENT_SERVICE_URL=http://nx-ms-server-event:3000
      - NODE_ENV=development
      - JWT_SECRET=this-is-a-secret-key-for-my-jwt-token-this-is-super-top-secret
    depends_on:
      - mongodb
      - nx-ms-server-auth
      - nx-ms-server-event
    networks:
      - app-network
    volumes:
      - ./nx-ms-server-gateway:/app
      - /app/node_modules
    restart: on-failure

  nx-ms-server-auth:
    build:
      context: ./nx-ms-server-auth
      dockerfile: Dockerfile.local
    container_name: nx-ms-server-auth
    ports:
      - 3001:3000
    environment:
      - GATEWAY_SERVICE_URL=http://nx-ms-server-gateway:3000
      - AUTH_SERVICE_URL=http://nx-ms-server-auth:3000
      - EVENT_SERVICE_URL=http://nx-ms-server-event:3000
      - JWT_SECRET=this-is-a-secret-key-for-my-jwt-token-this-is-super-top-secret
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/auth-db
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./nx-ms-server-auth:/app
      - /app/node_modules
    restart: on-failure

  nx-ms-server-event:
    build:
      context: ./nx-ms-server-event
      dockerfile: Dockerfile.local
    container_name: nx-ms-server-event
    ports:
      - 3002:3000
    environment:
      - GATEWAY_SERVICE_URL=http://nx-ms-server-gateway:3000
      - AUTH_SERVICE_URL=http://nx-ms-server-auth:3000
      - EVENT_SERVICE_URL=http://nx-ms-server-event:3000
      - JWT_SECRET=this-is-a-secret-key-for-my-jwt-token-this-is-super-top-secret
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/event-db
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./nx-ms-server-event:/app
      - /app/node_modules
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: