### 로그인
POST http://localhost:3000/api/auth/auth/login
content-type: application/json

{
  "email": "user1@test.com",
  "password": "test"
}

### 회원가입
POST http://localhost:3000/api/auth/user
content-type: application/json

{
  "email": "user1@test.com",
  "password": "test",
  "nickname": "testuser"
}
###
POST http://localhost:3000/api/auth/auth/refresh
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs

{
  "email": "user1@test.com",
  "refreshToken": "0a9cf89b-885f-4577-a321-2bebe2c5b182"
}

###
GET http://localhost:3000/api/auth/user/user2@test.com HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs
content-type: application/json

###
POST http://localhost:3000/api/auth/auth/verify
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs"
}
###
GET http://localhost:3000/api/event/event
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs
###
GET http://localhost:3000/api/event/event/682b4dce874767c7da623a48
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs

###
POST http://localhost:3000/api/event/event
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs

###
POST http://localhost:3000/api/event/claim
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs

{
  "eventId": "682b5a8ef50e6c09c3a46fd1"
}

### [유저] 보상 신청 이력 목록
GET http://localhost:3000/api/event/claim/my
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs

### [유저] 보상 신청 이력 상세
GET http://localhost:3000/api/event/claim/my/682b8feee6b7b39f577ebf3d
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwibmlja25hbWUiOiJ1c2VyMSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzQ3NzIwOTIzLCJleHAiOjE3NDc3NDI1MjN9.DsO88BqKEBeaKoy_0ETG9BBj30483fl7_7z0_cDWvhs
