export enum REWARD_TYPE {
  MEDAL = 'MEDAL',
  EXP_COUPON = 'EXP_COUPON',
  LEVELUP_POTION = 'LEVELUP_POTION',
  CHAIR = 'CHAIR',
  TITLE = 'TITLE',
  CASH_ITEM = 'CASH_ITEM',
  PET = 'PET',
  MILEAGE = 'MILEAGE',
  ACHIEVEMENT = 'ACHIEVEMENT',
}
